export { default as InputField } from './InputField'
export { default as Button } from './Button'
export { default as Loading } from './Loading'
export { default as HeaderLaptop } from './HeaderLaptop'
export { default as HeaderMobile } from './HeaderMobile'
export { default as Search } from './Search'
export { default as Slider } from './Slider'
export { default as HomeItem } from './HomeItem'
export { default as ProductItem } from './ProductItem'
export { default as Footer } from './Footer'

